-- Generated by scripts/generate-seed.mjs — do not edit by hand.
-- Run in Supabase SQL Editor after schema.sql.

insert into public.courses (id, title, price_inr, sort) values ('agentic-ai', 'Agentic AI Development', 4999, 1)
  on conflict (id) do update set title = excluded.title, sort = excluded.sort;
insert into public.projects (course_id, week, title, brief, max_marks, sort) values
  ('agentic-ai', 1, 'CLI quiz game', 'A terminal quiz that loads 10+ questions, asks them in random order, tracks score and shows a final result with percentage.', 10, 1),
  ('agentic-ai', 2, 'Personal expense tracker', 'A command-line app to add, list, filter and summarise expenses by category and month.', 10, 2),
  ('agentic-ai', 3, 'Weather + news API service', 'A FastAPI service that, given a city, fetches current weather and top headlines concurrently and returns combined JSON. Optional simple HTML page.', 10, 3),
  ('agentic-ai', 4, 'College database query set', 'Given a students / courses / enrollments / marks / attendance database, write 25 queries of increasing difficulty and document what each one answers.', 10, 4),
  ('agentic-ai', 5, 'Canteen / library management API (Phase 1 project)', 'Design the database, then build a FastAPI + PostgreSQL service with full CRUD and reports built in SQL.', 20, 5),
  ('agentic-ai', 6, 'Prompt-powered study assistant', 'A Streamlit or CLI app where students paste notes; it summarises them, generates flashcards and quizzes the user.', 10, 6),
  ('agentic-ai', 7, 'Tool-using assistant', 'A chatbot with a calculator, live weather lookup and read-only tools over the Phase 1 database (e.g. ''which items sold most this week?''); the model decides which tool (if any) to use.', 10, 7),
  ('agentic-ai', 8, 'College handbook RAG bot (Phase 2 project)', 'Ingest real college PDFs (syllabus, rules, placement guides) into pgvector and answer questions with cited sources through a Streamlit or web UI.', 20, 8),
  ('agentic-ai', 9, 'Web research agent (no framework)', 'Given a question, the agent searches the web, reads pages and writes a short report with citations.', 10, 9),
  ('agentic-ai', 10, 'Personal task agent', 'A chat agent that manages a to-do list and simple schedule stored in Postgres and remembers user preferences across sessions.', 10, 10),
  ('agentic-ai', 11, 'Natural-language analytics agent', 'An agent over a sample sales or college database: users ask questions in plain English; it writes safe SQL, runs it, explains the answer and draws a simple chart.', 10, 11),
  ('agentic-ai', 12, 'Multi-agent content team (Phase 3 project, teams)', 'A researcher, writer and reviewer agent produce a blog post or report on a given topic, with a human approval step before ''publishing''.', 20, 12),
  ('agentic-ai', 13, 'Live streaming chat agent', 'A web chat where the agent streams its answer token by token and shows each tool call as it happens.', 10, 13),
  ('agentic-ai', 14, 'Choose one: voice assistant or live market-watch agent', 'Option A: a voice assistant for campus FAQs. Option B: an agent that logs stock / crypto prices or news to Postgres and sends an explained alert on Telegram or Discord when conditions are met.', 10, 14),
  ('agentic-ai', 15, 'Deploy and evaluate the capstone', 'Each team deploys its capstone and runs its full evaluation set.', 10, 15),
  ('agentic-ai', null, 'Capstone project', 'Teams of 2-4 build and deploy a real-time AI agent, backed by a database, that solves a real problem. The capstone is worth 35% of the final grade and is the centrepiece of each student''s portfolio. It must use at least 3 tools, a PostgreSQL database with a designed schema, at least one real-time feature, persistent memory, a human approval step before risky actions, a 20+ task evaluation set, safety measures, and be deployed at a public URL with a GitHub repo and demo video.', 100, 16)
  on conflict (course_id, sort) do update set week = excluded.week, title = excluded.title, brief = excluded.brief;

insert into public.courses (id, title, price_inr, sort) values ('ml-dl-transformers', 'ML, Deep Learning & Transformers', 7999, 2)
  on conflict (id) do update set title = excluded.title, sort = excluded.sort;
insert into public.projects (course_id, week, title, brief, max_marks, sort) values
  ('ml-dl-transformers', 1, 'Student report-card generator', 'Reads marks for a class, calculates totals, percentages, grades and rank, and prints formatted report cards.', 10, 1),
  ('ml-dl-transformers', 2, 'Personal expense tracker', 'A class-based app to add, filter and summarise expenses by category and month, stored in CSV.', 10, 2),
  ('ml-dl-transformers', 3, 'Image filters with NumPy', 'Load a photo as an array and implement filters without image libraries.', 10, 3),
  ('ml-dl-transformers', 4, 'EDA report on a real dataset (Phase 1 project)', 'Pick an Indian open dataset (IPL, air quality, crop production, census, etc.) and produce an EDA notebook.', 20, 4),
  ('ml-dl-transformers', 5, 'Gradient descent visualiser + probability simulations', 'Animate gradient descent on 2D functions and run Monte Carlo simulations.', 10, 5),
  ('ml-dl-transformers', 6, 'House price predictor', 'Predict house prices with a from-scratch model and scikit-learn, and compare.', 10, 6),
  ('ml-dl-transformers', 7, 'SMS spam or placement predictor', 'Train at least 3 classifiers, compare them, and analyse the mistakes.', 10, 7),
  ('ml-dl-transformers', 8, 'In-class Kaggle-style competition (teams)', 'Teams compete on a private leaderboard (e.g. loan default prediction).', 10, 8),
  ('ml-dl-transformers', 9, 'Customer segmentation', 'Cluster retail customers and describe each segment.', 10, 9),
  ('ml-dl-transformers', 10, 'End-to-end deployed ML app (Phase 2 project)', 'From raw data to a deployed app (e.g. crop recommendation, loan approval, student dropout risk).', 20, 10),
  ('ml-dl-transformers', 11, 'NumPy neural network on MNIST', 'A 2-layer network in pure NumPy that recognises handwritten digits.', 10, 11),
  ('ml-dl-transformers', 12, 'Fashion-MNIST classifier', 'Train and improve an MLP in PyTorch.', 10, 12),
  ('ml-dl-transformers', 13, 'Plant disease or Indian food classifier', 'Fine-tune a pretrained CNN on a real image dataset.', 10, 13),
  ('ml-dl-transformers', 14, 'Review sentiment analyser', 'An LSTM classifier for movie or product reviews (English or a regional language).', 10, 14),
  ('ml-dl-transformers', 15, 'Deployed deep learning app (Phase 3 project)', 'Train a vision or text model with tracked experiments and deploy it on Hugging Face Spaces.', 20, 15),
  ('ml-dl-transformers', 16, 'Transformer block from scratch', 'Implement attention and a full Transformer block in PyTorch.', 10, 16),
  ('ml-dl-transformers', 17, 'Mini GPT', 'Train a small GPT on a text corpus (e.g. Thirukkural, Tamil / Hindi news, Shakespeare) and generate text.', 10, 17),
  ('ml-dl-transformers', 18, 'Fine-tuned BERT model', 'Fine-tune DistilBERT or a multilingual model (e.g. IndicBERT) for news classification or NER.', 10, 18),
  ('ml-dl-transformers', 19, 'LoRA fine-tuned domain assistant (Phase 4 project)', 'Fine-tune a small open LLM (1-3B) on a domain dataset (e.g. college FAQs) and compare approaches.', 20, 19),
  ('ml-dl-transformers', null, 'Capstone project', 'Teams of 2-4 train or fine-tune a model and deploy it to solve a real problem. The capstone is worth 35% of the final grade and is the centrepiece of each student''s portfolio. Minimum requirements: a real dataset (public or collected) with its source and licence documented; a simple baseline and at least one deep learning or Transformer model that beats it; tracked experiments (W&B or MLflow) with a clear evaluation metric; error analysis and a basic bias / fairness check; and a deployed app or API, a GitHub repo with README, a model card and a demo video. Teams may propose their own idea if it meets the minimum requirements.', 100, 20)
  on conflict (course_id, sort) do update set week = excluded.week, title = excluded.title, brief = excluded.brief;

insert into public.courses (id, title, price_inr, sort) values ('data-science', 'Data Science', 4999, 3)
  on conflict (id) do update set title = excluded.title, sort = excluded.sort;
insert into public.projects (course_id, week, title, brief, max_marks, sort) values
  ('data-science', 1, 'Cricket scorecard analyser', 'Reads ball-by-ball data for an innings and reports runs, strike rates, boundaries and top performers.', 10, 1),
  ('data-science', 2, 'Student records manager', 'Add, search, update and summarise student records stored in CSV.', 10, 2),
  ('data-science', 3, 'Movies / OTT titles analysis', 'Answer 15 business questions about a streaming catalogue with Pandas.', 10, 3),
  ('data-science', 4, 'Messy-data clean-up', 'Clean a deliberately messy real dataset (e.g. Indian real-estate listings) and publish a tidy version.', 10, 4),
  ('data-science', 5, 'E-commerce query set', 'Write 25 queries of increasing difficulty on an orders / customers / products database.', 10, 5),
  ('data-science', 6, 'Retail sales analysis (Phase 1 project)', 'Load raw CSVs into PostgreSQL and answer business questions with SQL and Pandas.', 20, 6),
  ('data-science', 7, 'Chart makeover + interactive EDA', 'Redesign 5 bad charts, then build an interactive EDA of an Indian open dataset (e.g. state-wise air quality).', 10, 7),
  ('data-science', 8, 'IPL player consistency report', 'Rank batters and bowlers on consistency, not just averages, using descriptive statistics.', 10, 8),
  ('data-science', 9, 'Test five claims with data', 'Test real claims (e.g. ''students with coaching score higher'', ''weekend sales are higher'').', 10, 9),
  ('data-science', 10, 'A/B test and pricing analysis', 'Analyse a website A/B test and estimate how price and discounts affect sales.', 10, 10),
  ('data-science', 11, 'Business dashboard + memo (Phase 2 project)', 'Build an interactive KPI dashboard for a business dataset (e.g. food delivery or retail chain) and a memo to the ''CEO''.', 20, 11),
  ('data-science', 12, 'Used-car price predictor', 'Predict used-car prices (e.g. CarDekho data) and explain what drives price.', 10, 12),
  ('data-science', 13, 'Customer churn predictor', 'Predict telecom churn and recommend which customers to target for retention.', 10, 13),
  ('data-science', 14, 'In-class Kaggle-style competition (teams)', 'Teams compete on a private leaderboard (e.g. credit default).', 10, 14),
  ('data-science', 15, 'Segmentation + product recommender', 'Segment e-commerce customers and build a ''customers also bought'' recommender.', 10, 15),
  ('data-science', 16, 'Retail demand forecast (Phase 3 project)', 'Forecast store or product demand for the next 8 weeks and recommend inventory levels.', 20, 16),
  ('data-science', 17, 'Review sentiment and topic analysis', 'Analyse thousands of product or app reviews for sentiment trends and complaint topics.', 10, 17),
  ('data-science', 18, 'PySpark pipeline', 'Clean and aggregate a multi-million-row dataset (e.g. NYC taxi trips or Indian railways data).', 10, 18),
  ('data-science', 19, 'Deployed model with model card', 'Deploy a Phase 3 model as an API or app for others to use.', 10, 19),
  ('data-science', null, 'Capstone project', 'Teams of 2-4 take a real business or social question from raw data to a recommendation backed by analysis, a model and a dashboard, worth 35% of the final grade. Minimum requirements: real data from at least two sources stored and queried with SQL; a statistical analysis (hypothesis test, A/B test or regression) and a predictive or forecasting model that beats a baseline; an interactive dashboard or app; a written recommendation for a named decision-maker with limitations stated; and a GitHub repo with README, model card, fairness and privacy notes and a demo video. Teams may propose their own idea if it meets the minimum requirements.', 100, 20)
  on conflict (course_id, sort) do update set week = excluded.week, title = excluded.title, brief = excluded.brief;
