// Generates supabase/seed.sql from content/courses/*.json.
// Usage: npm run seed:generate
// Safe to re-run: courses keep their current price/batch, projects are upserted by (course_id, sort).

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dir = join(root, "content", "courses");

const q = (s) => (s == null ? "null" : `'${String(s).replace(/'/g, "''")}'`);

const courses = readdirSync(dir)
  .filter((f) => f.endsWith(".json"))
  .map((f) => JSON.parse(readFileSync(join(dir, f), "utf8")))
  .sort((a, b) => a.sort - b.sort);

const lines = [
  "-- Generated by scripts/generate-seed.mjs — do not edit by hand.",
  "-- Run in Supabase SQL Editor after schema.sql.",
  "",
];

for (const c of courses) {
  lines.push(
    `insert into public.courses (id, title, price_inr, sort) values (${q(c.slug)}, ${q(c.shortTitle)}, ${c.defaultPrice}, ${c.sort})`,
    `  on conflict (id) do update set title = excluded.title, sort = excluded.sort;`,
  );

  let sort = 0;
  const rows = c.weeks
    .filter((w) => w.project)
    .map((w) => {
      sort += 1;
      const isPhase = /phase \d project/i.test(w.project.title);
      return [c.slug, w.week, w.project.title, w.project.brief, isPhase ? 20 : 10, sort];
    });
  rows.push([c.slug, null, "Capstone project", c.capstone.summary, 100, sort + 1]);

  lines.push(
    `insert into public.projects (course_id, week, title, brief, max_marks, sort) values`,
    rows
      .map(([cid, week, title, brief, max, s]) => `  (${q(cid)}, ${week ?? "null"}, ${q(title)}, ${q(brief)}, ${max}, ${s})`)
      .join(",\n"),
    `  on conflict (course_id, sort) do update set week = excluded.week, title = excluded.title, brief = excluded.brief;`,
    "",
  );
}

writeFileSync(join(root, "supabase", "seed.sql"), lines.join("\n"));
console.log(`Wrote supabase/seed.sql (${courses.length} courses)`);
